### ISSUE TITLE
Issue with internationalization/localization on login screen

### ISSUE THREAD

**Issue by fabiancdng** [iTechnious/BulletFlask#2]
The translations using `react-i18next`'s `t()` function seems to work everywhere except for the login screen.
The problem I think has something to do with the translations being accessed before they are fully initialized (see console output)?
I'd appreciate if you could to look into that @AuxiliumCDNG.

![image](https://user-images.githubusercontent.com/36338179/147695664-5e4e1d44-57b8-42d3-83b2-d459a980ca62.png)

Once you sign in (or try to and the attempt fails) it's fine again:
![image](https://user-images.githubusercontent.com/36338179/147695776-025aad4e-6121-4f0b-8ecc-259b047c3e75.png)

**Comment by AuxiliumCDNG** [comment]
This is because the "error"-code returned by the api will interrupt the suspense feature, I think.
This may be fixed by catching the errors...
This is also why the login screen works when logging out.

**Comment by AuxiliumCDNG** [comment]
This does not seem to be the problem after all...
I'm on it xD

**Comment by AuxiliumCDNG** [comment]
I think there is a general issue with waiting for the translations.
I suspect it works on the forum page because it has to fetch the API first. In that time the translations load.
The login screen works on error since it is rendered again with the translations already loaded.
Information on how i18n works with the react-router is a bit sparse but is think it has something to do with that.

**Comment by fabiancdng** [comment]
@AuxiliumCDNG I think I figured this out. Getting the `t()` function via the `useTranslation()` hook inside the component as opposed to importing it from 'i18next' seems to do the trick.


See 65a0add.

**Comment by fabiancdng** [comment]
Tested it, seems to work. I'll close this for now, feel free to re-open when there are still translations not loading up somewhere.
